### ISSUE TITLE
Migrate public API to use Span<T>/ReadOnlySpan<T> thu-out

### ISSUE THREAD

**Issue by tocsoft** [SixLabors/Shapes#18]
Update the public API to make use of Span<T>/ReadOnlySpan<T> instead of arrays.

**Comment by JimBobSquarePants** [comment]
We should get this migrated now since there are now methods in ImageSharp that require the change to remove unnecessary allocations.

https://github.com/SixLabors/ImageSharp/blob/51a167115b7af0a5cd9e575cc23af346273627b0/src/ImageSharp.Drawing/Paths/ShapePath.cs#L25

**Comment by antonfirsov** [comment]
Isn't this fixed with #41?

**Comment by JimBobSquarePants** [comment]
I think so yes

**Comment by tocsoft** [comment]
yup
