### ISSUE TITLE
GenerateOutline as used in ImageSharp produces wrong results with self-intersecting lines

### ISSUE THREAD

**Issue by Symbiatch** [SixLabors/Shapes#19]
I am not sure if this bug is in the way ImageSharp uses `GenerateOutline` or if this is a bug in this library. I'm posting it here first, will gladly move it to ImageSharp if the problem is on that side.

I have code that draws lines that may intersect themselves in the exact same point. In this case it seems that GenerateOutline assumes it's a closed path and stops drawing anything after this point.

Here's the simplest code to demonstrate the problem:

```using System.Numerics;
using ImageSharp;
using ImageSharp.Drawing.Pens;
using ImageSharp.PixelFormats;
using System.IO;

namespace ConsoleApp1
{
	class Program
	{
		static void Main(string[] args)
		{
			using (var image = new Image<Argb32>(256, 256))
			{
				image.Fill(new Argb32(0, 0, 0));

				var pen1 = new Pen<Argb32>(new Argb32(255, 0, 0), 5f);
				var line1 = new Vector2[] { new Vector2(117f, 199f), new Vector2(31f, 210f), new Vector2(35f, 191f), new Vector2(117f, 199f), new Vector2(2f, 9f) };

				image.DrawLines(pen1, line1);

				var pen2 = new Pen<Argb32>(new Argb32(0, 255, 0), 5f);
				var line2 = new Vector2[] { new Vector2(217f, 199f), new Vector2(131f, 210f), new Vector2(135f, 191f), new Vector2(217f, 199.001f), new Vector2(2f, 9f) };

				image.DrawLines(pen2, line2);

				image.SaveAsPng(File.OpenWrite(@"isharp.png"));
			}
		}
	}
}
```

The result is this:

![isharp](https://cloud.githubusercontent.com/assets/2326085/26717440/16e6c3e2-4786-11e7-83c5-4f8eba98acd4.png)

The red line that has identical points will stop drawing at that point but a small difference will allow it to continue.

The first line generates this kind of outline shape (first of the two):

![sloutline1](https://cloud.githubusercontent.com/assets/2326085/26717523/66ffdc24-4786-11e7-8f14-ab4303bb646d.png)

The second one:

![sloutline2](https://cloud.githubusercontent.com/assets/2326085/26717528/6ca08264-4786-11e7-8690-87e698c9d48d.png)

As said I'm not sure if `GenerateOutline` is supposed to work like this, in which case ImageSharp needs to fix this, or if it's a bug in this library. If there's any other information needed I'll be happy to help.

Running on SixLabors.Shapes 0.1.0-alpha0016, ImageSharp 1.0.0-alpha9-00112, ImageSharp.Drawing 1.0.0-alpha9-00107

**Comment by tocsoft** [comment]
this definitely a bug in here.. i'll look at this as soon as I can.

by the way thanks for the really informative issue 👍

**Comment by tocsoft** [comment]
This should now be fixed in SixLabors.Shapes 0.1.0-alpha0017 however there are breaking changes in SixLabors.Shapes that are waiting on JimBobSquarePants/ImageSharp#240 being merged before you will be able to move up to the latest.
