### ISSUE TITLE
System.MissingMethodException

### ISSUE THREAD

**Issue by KingKnecht** [SixLabors/Shapes#22]
Hi,
when starting the example program I get following exception:

> System.MissingMethodException: 'Method not found: 'SixLabors.Shapes.Rectangle SixLabors.Shapes.IPath.get_Bounds()'.'<

at 
`img.Fill(Rgba32.HotPink, s, new ImageSharp.GraphicsOptions(true));`

Why does this even compile? Is there some reflection involved?
Thx,
Sven

**Comment by tocsoft** [comment]
Looks like you've managed to end up with old versions of the libraries please make sure your using the latest release. ImageSharp, ImageSharp.Drawing and SixLabors.Shapes.

**Comment by KingKnecht** [comment]
I have cloned the repo. The referenced NuGets are:
ImageSharp: 1.0.0-alpha9-00139
ImageSharp.Drawing: 1.0.0-alpha9-00134

Is that wrong?

**Comment by tocsoft** [comment]
current versions of imagesharp are 

ImageSharp.Drawing  @ 1.0.0-alpha9-00177 
ImageSharp  @ 1.0.0-alpha9-00182

with ImageSharp.Drawing  depending on 
SixLabors.Shapes.Text @ 0.1.0-alpha0018
SixLabors.Shapes @ 0.1.0-alpha0018

The error looks like your project has pulled down a version of SixLabors.Shapes thats incompatible with build 00134 of ImageSharp.Drawing if you make sure your on the latest versions you should be fine.

**Comment by KingKnecht** [comment]
Hmm, I expected to see the used/required versions in the NuGet.config file. But there are only urls and no packages and their versions as I'm used to.
I don't know how to change the required versions.
If you clone this repo, you can build and run the sample app? 
Again, I don't understand why this does even compile, I mean it expects to have a getter for property "Bounds". It shouldn't compile.
Maybe I don't understand the .Net Core stuff good enough...

**Comment by KingKnecht** [comment]
If I check IPath.cs there is a property Bounds:
```
        /// <summary>
        /// Gets the bounds enclosing the path
        /// </summary>
        RectangleF Bounds { get; }
```

**Comment by JimBobSquarePants** [comment]
This problem should be long gone now as we've had multiple depencency updates and releases since. 

I'm closing this for now.
