### ISSUE TITLE
Q: Use case of library

### ISSUE THREAD

**Issue by KingKnecht** [SixLabors/Shapes#23]
Hi,
very general questions: What would be a use case of your library? Say, I want do develop a diagram designer and the graphics core should be cross-platform. Would I use it then? If I have a WPF client how would I render those shapes? Then I need a piece of code translating your shapes into visuals of WPF?  Would I have access to all the data needed to render those shapes in WPF? How would I do dragging, selecting etc? Your shapes don't support such things (MouseEvents).

Sorry, it's very confusing for me at the moment. Any help would be greatly appreciated,
Sven

**Comment by tocsoft** [comment]
This shapes library is primarily designed for use in https://github.com/SixLabors/ImageSharp for its vector graphics rendering subsystem. Its not designed been designed for use in a designer for diagrams directly but could be used indirectly to help you track bounding boxes of your shapes and draw your vectors but you would have to layer an interactive subsystem over it. 

Basically at the moment the focus is on having a library that can describe complex shapes for use in canvas drawing scenarios which is how ImageSharp uses it.

We expose the full/final path data so you would able to use that to generate wpf vectors for rendering in WPF but its not really a focus of this library at this time. You can get the point data using `shape.Flatten()` and that will return the final path that could be take and used to build a shape in WPF.

**Comment by KingKnecht** [comment]
Ok, as far as I understand ImageSharp uses "Shapes" to render them into a bitmap with characteristics of vector drawings (no blurry edges etc). Cool. That means I could provide another renderer responsible for rendering to a WPF canvas, right? One question: Where does the input come from for ImageSharp? I mean at the end of the day the user must be able to create, move, scale, shapes and then click "Save as image". Providing this functionality is exactly the problem I'm facing now.

**Comment by tocsoft** [comment]
The best example I have right now is this 
https://github.com/SixLabors/ImageSharp/blob/a710ccca3a2eb993bdc591b701660a4d6c66c92f/samples/AvatarWithRoundedCorner/Program.cs#L37-L68

Shape manipulation followed by drawing it to the image.

**Comment by KingKnecht** [comment]
Thx, I will investigate that.
Here is an example of what I'm doing:
[Youtube Demo App](https://www.youtube.com/watch?v=CspnDtihXGA)
I'm using my own clumsy abstraction of shapes to be independent of the WPF Geometry/Shapes stuff.
