### ISSUE TITLE
Incorrect Usage of RectangularPolygon(TopLeft, BottomRight) constructor in overload

### ISSUE THREAD

**Issue by adragoset** [SixLabors/Shapes#26]
```
/// <summary>
        /// Initializes a new instance of the <see cref="RectangularePolygon" /> class.
        /// </summary>
        /// <param name="x">The x.</param>
        /// <param name="y">The y.</param>
        /// <param name="width">The width.</param>
        /// <param name="height">The height.</param>
        public RectangularePolygon(float x, float y, float width, float height)
            : this(new PointF(x, y), new SizeF(width, height))
        {
        }

public RectangularePolygon(PointF location, SizeF size)
            : this(location, location + size)
        {
        }
```

I believe this is wrong. If you Use the overload correctly you should be passing in the top left corner as the location and ```new SizeF(width, height)``` should equate to the lower right hand corner  however the overload location + size inverts your rectangle and makes the location the bottom left corner and the location + size becomes the top right corner. This ends up inverting all of the named corners in the rectangle and also messes with some other methods. To overcome this you have to pass in negative y values for the height of your rectangle to get the actual rectangle you wanted.

**Comment by JimBobSquarePants** [comment]
@tocsoft Could I get a second pair of eyes on this when you get a chance please. I've had a look an the constructors all look correct to me.

**Comment by tocsoft** [comment]
closing as it seems right to me too, if you believe it is still an issued please provide a reproduction of the issues with input values and expected outputs that we can use to add a unit tests.
