### ISSUE TITLE
Pencil width is always 2 pixels.

### ISSUE THREAD

**Issue by garciaolais** [SixLabors/Shapes#46]
### Prerequisites
- [x]  I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I need to create a rectangle of 10 x 10 pixels ,width 1 pixel, but I can only obtain width of 2 pixels.

Obtained result

![obtenido](https://user-images.githubusercontent.com/14133711/41213059-3d2675a4-6d08-11e8-9800-58cf8e9a6a80.jpg)

Desired result

![deseado](https://user-images.githubusercontent.com/14133711/41213060-41bfc822-6d08-11e8-86d4-9cf9559d30b4.jpg)

### Steps to Reproduce

```
            var width = 32;
            var height = 32;            
            var name = "Rectangle";
            
            using (Image<Rgba32> image = new Image<Rgba32>(width, height))
            {
                Rectangle rect = new Rectangle(0, 0, 10, 10);
                Pen<Rgba32> pen = new Pen<Rgba32>(Rgba32.White, 1f);
                image.Mutate(i => i.Draw(pen, rect));                
                image.Save(name+".bmp");
            }
```

### System Configuration

- ImageSharp version: **1.0.0-beta0004**
- Other ImageSharp packages and versions: **SixLabors.ImageSharp.Drawing 1.0.0-beta0004**
- Environment (Operating system, version and so on): **Win 10 Pro build 17134**
- .NET Framework version:**.Net Core 2.0**
- Additional information:

**Comment by tocsoft** [comment]
try drawing on the half pixel, as i believe we are drawing on the grid between pixels on on the pixel itself i.e try using `new Rectangle(0.5, 0.5, 10, 10)` instead. 

_I reserve to right to be completely wrong on this it was a while ago I wrote the rasterizing code._

**Comment by garciaolais** [comment]
Thank you very much for your reply.

Try to follow its recommendations but the Rectangle does not support float.

```
public Rectangle(Point point, Size size);
public Rectangle(int x, int y, int width, int height);
```

**Comment by garciaolais** [comment]
After trying different examples , I was find a solution. 😄 

```
using (var image = new Image<Rgba32>(128, 32))
{
    image.Mutate(x => x
        .BackgroundColor(Rgba32.Black)
        .Draw(
            new GraphicsOptions(false),
            Rgba32.White,
            1,
            new Rectangle(0, 1, 10, 10)
            ));
    image.Save(name + ".bmp");
}
```
